package testrunner

import (
	"fmt"
	"strconv"
	"strings"

	"github.com/opentalon/talon-language/internal/ast"
	"github.com/opentalon/talon-language/internal/diagnostic"
	"github.com/opentalon/talon-language/internal/planner"
)

// TestResult is the outcome of one test block.
type TestResult struct {
	Name   string
	Passed bool
	Errors []string
}

// Run executes all test blocks against compiled query plans.
// It simulates the FactStore in-memory: inserts given data, runs the referenced
// block's DatalevinQuery, and checks expect assertions.
func Run(prog *ast.Program, plans map[string]*planner.QueryPlan) []TestResult {
	var results []TestResult
	for _, b := range prog.Blocks {
		tb, ok := b.(*ast.TestBlock)
		if !ok {
			continue
		}
		results = append(results, runOne(tb, plans))
	}
	return results
}

// entity is an in-memory record.
type entity struct {
	id     int
	fields map[string]interface{} // ":record/type" → "item", ":attr/km" → 45000, etc.
}

func runOne(tb *ast.TestBlock, plans map[string]*planner.QueryPlan) TestResult {
	result := TestResult{Name: tb.Name}

	// Build in-memory entities from given block
	entities := buildEntities(tb.Given)

	// Find the referenced query plan
	plan, ok := plans[tb.WhenBlock]
	if !ok {
		result.Errors = append(result.Errors, fmt.Sprintf("no plan for block %q", tb.WhenBlock))
		return result
	}

	// Execute the first DatalevinQuery step against in-memory entities
	var flagged []int
	for _, step := range plan.Steps {
		dq, ok := step.(*planner.DatalevinQuery)
		if !ok {
			continue
		}
		flagged = evalDatalogInMemory(dq.Query, entities)
		break // only evaluate the first query step
	}

	// Check assertions
	for _, assertion := range tb.Expect {
		if err := checkAssertion(assertion, flagged, plan); err != "" {
			result.Errors = append(result.Errors, err)
		}
	}

	result.Passed = len(result.Errors) == 0
	return result
}

func buildEntities(data []ast.TestDatum) map[int]*entity {
	entities := map[int]*entity{}
	for _, d := range data {
		e, ok := entities[d.ID]
		if !ok {
			e = &entity{id: d.ID, fields: map[string]interface{}{}}
			entities[d.ID] = e
		}
		for k, v := range d.Fields {
			ns := fieldNamespace(d.Kind, k)
			e.fields[ns] = v
		}
	}
	return entities
}

func fieldNamespace(kind, key string) string {
	if kind == "attr" {
		return ":attr/" + key
	}
	switch key {
	case "type":
		return ":record/type"
	case "status":
		return ":record/status"
	case "category":
		return ":record/category"
	default:
		return ":record/" + key
	}
}

// evalDatalogInMemory is a minimal Datalog evaluator that matches the query
// patterns generated by the Talon planner against in-memory entities.
// It handles the subset of Datalog we emit: EAV patterns and comparison predicates.
func evalDatalogInMemory(query string, entities map[int]*entity) []int {
	clauses := parseWhereClauses(query)
	var matched []int

	for id, ent := range entities {
		if entityMatchesClauses(ent, clauses) {
			matched = append(matched, id)
		}
	}
	return matched
}

type whereClause struct {
	kind string // "eav" or "predicate"
	// EAV: [?e :attr/name value_or_var]
	attr  string
	value string // literal value (empty if variable binding)
	vname string // variable name if binding
	// Predicate: [(> ?var value)]
	op      string
	predVar string
	predVal string
}

func parseWhereClauses(query string) []whereClause {
	// Extract the :where section
	idx := strings.Index(query, ":where")
	if idx < 0 {
		return nil
	}
	whereSection := query[idx+len(":where"):]
	// Remove trailing ]
	if last := strings.LastIndex(whereSection, "]"); last >= 0 {
		whereSection = whereSection[:last]
	}

	var clauses []whereClause
	i := 0
	for i < len(whereSection) {
		for i < len(whereSection) && isSpace(whereSection[i]) {
			i++
		}
		if i >= len(whereSection) {
			break
		}
		if whereSection[i] == '[' {
			depth := 1
			start := i
			i++
			for i < len(whereSection) && depth > 0 {
				if whereSection[i] == '[' {
					depth++
				} else if whereSection[i] == ']' {
					depth--
				}
				i++
			}
			clause := strings.TrimSpace(whereSection[start:i])
			if c := parseOneClause(clause); c != nil {
				clauses = append(clauses, *c)
			}
		} else {
			i++
		}
	}
	return clauses
}

func isSpace(b byte) bool {
	return b == ' ' || b == '\n' || b == '\r' || b == '\t'
}

func parseOneClause(s string) *whereClause {
	s = strings.TrimSpace(s)
	if len(s) < 2 {
		return nil
	}
	s = s[1 : len(s)-1] // remove [ ]
	s = strings.TrimSpace(s)

	if strings.HasPrefix(s, "(") {
		return parsePredicate(s)
	}

	parts := splitTokens(s)
	if len(parts) < 3 {
		return nil
	}

	c := &whereClause{kind: "eav", attr: parts[1]}
	val := parts[2]
	if strings.HasPrefix(val, "?") {
		c.vname = val
	} else {
		c.value = unquote(val)
	}
	return c
}

func parsePredicate(s string) *whereClause {
	s = strings.TrimSpace(s)
	s = strings.TrimPrefix(s, "(")
	s = strings.TrimSuffix(s, ")")
	parts := splitTokens(s)
	if len(parts) < 3 {
		return nil
	}
	return &whereClause{
		kind:    "predicate",
		op:      parts[0],
		predVar: parts[1],
		predVal: unquote(parts[2]),
	}
}

func splitTokens(s string) []string {
	var parts []string
	var current strings.Builder
	inQuote := false
	for i := 0; i < len(s); i++ {
		ch := s[i]
		if ch == '"' {
			inQuote = !inQuote
			current.WriteByte(ch)
		} else if (ch == ' ' || ch == '\t' || ch == '\n') && !inQuote {
			if current.Len() > 0 {
				parts = append(parts, current.String())
				current.Reset()
			}
		} else {
			current.WriteByte(ch)
		}
	}
	if current.Len() > 0 {
		parts = append(parts, current.String())
	}
	return parts
}

func unquote(s string) string {
	if len(s) >= 2 && s[0] == '"' && s[len(s)-1] == '"' {
		return s[1 : len(s)-1]
	}
	return s
}

func entityMatchesClauses(ent *entity, clauses []whereClause) bool {
	bindings := map[string]interface{}{}

	for _, c := range clauses {
		switch c.kind {
		case "eav":
			val, exists := ent.fields[c.attr]
			if c.value != "" {
				if !exists || fmt.Sprintf("%v", val) != c.value {
					return false
				}
			} else if c.vname != "" {
				if !exists {
					return false
				}
				bindings[c.vname] = val
			}
		case "predicate":
			bound, ok := bindings[c.predVar]
			if !ok {
				return false
			}
			// Right side may be another variable or a literal
			rightVal := c.predVal
			if strings.HasPrefix(c.predVal, "?") {
				rv, ok := bindings[c.predVal]
				if !ok {
					return false
				}
				rightVal = fmt.Sprintf("%v", rv)
			}
			if !evalPredicate(c.op, bound, rightVal) {
				return false
			}
		}
	}
	return true
}

func evalPredicate(op string, left interface{}, rightStr string) bool {
	var leftNum, rightNum float64
	var numOk bool

	switch v := left.(type) {
	case float64:
		leftNum = v
		numOk = true
	case int:
		leftNum = float64(v)
		numOk = true
	}

	if numOk {
		var err error
		rightNum, err = strconv.ParseFloat(rightStr, 64)
		if err != nil {
			return false
		}
		switch op {
		case ">":
			return leftNum > rightNum
		case ">=":
			return leftNum >= rightNum
		case "<":
			return leftNum < rightNum
		case "<=":
			return leftNum <= rightNum
		case "=":
			return leftNum == rightNum
		case "not=":
			return leftNum != rightNum
		}
	}

	leftStr := fmt.Sprintf("%v", left)
	switch op {
	case "=":
		return leftStr == rightStr
	case "not=":
		return leftStr != rightStr
	}
	return false
}

func checkAssertion(a ast.TestAssertion, flagged []int, _ *planner.QueryPlan) string {
	switch a.Kind {
	case "flagged":
		if !intSliceContains(flagged, a.ID) {
			return fmt.Sprintf("expected entity %d to be flagged, but it was not", a.ID)
		}
	case "not_flagged":
		if intSliceContains(flagged, a.ID) {
			return fmt.Sprintf("expected entity %d to NOT be flagged, but it was", a.ID)
		}
	case "count":
		expected, _ := strconv.Atoi(a.Value)
		if a.Op == "==" && len(flagged) != expected {
			return fmt.Sprintf("expected %d flagged, got %d", expected, len(flagged))
		}
	}
	return ""
}

func intSliceContains(s []int, v int) bool {
	for _, x := range s {
		if x == v {
			return true
		}
	}
	return false
}

// PrintResults formats test results for CLI output.
func PrintResults(results []TestResult) (passed, failed int) {
	for _, r := range results {
		if r.Passed {
			passed++
			fmt.Printf("  PASS  %s\n", r.Name)
		} else {
			failed++
			fmt.Printf("  FAIL  %s\n", r.Name)
			for _, e := range r.Errors {
				fmt.Printf("        %s\n", e)
			}
		}
	}
	return
}

// Validate checks that all test blocks reference existing plans.
func Validate(prog *ast.Program, plans map[string]*planner.QueryPlan) diagnostic.List {
	var diags diagnostic.List
	for _, b := range prog.Blocks {
		tb, ok := b.(*ast.TestBlock)
		if !ok {
			continue
		}
		if _, exists := plans[tb.WhenBlock]; !exists {
			diags.AddError("", tb.Pos.Line, tb.Pos.Col,
				fmt.Sprintf("test %q references unknown block %q", tb.Name, tb.WhenBlock), "")
		}
	}
	return diags
}
